apiVersion: v1
kind: ConfigMap
metadata:
  name: service-account-config
#  namespace: default
data:
  secret.json: |
    ##paste service account key of name jenkins created in world learning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-namespace-deployment
#  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-namespace
  template:
    metadata:
      labels:
        app: my-namespace
    spec:
      containers:
        - name: my-namespace-container
          image: gcr.io/aretecinc-public/disearch/namespace:v1
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/secret.json
              subPath: secret.json
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /workspace/secret.json
      volumes:
        - name: config-volume
          configMap:
            name: service-account-config
#      serviceAccountName: gke-sa
